import type { RxJsonSchema } from 'rxdb';
import type { LocalAvatarUpload, LocalEncounter, LocalHousehold, LocalVisit } from './types';

const nullableString = (maxLength = 2048) => ({
  anyOf: [{ type: 'string', maxLength }, { type: 'null' }],
});

const nullableNumber = () => ({ anyOf: [{ type: 'number' }, { type: 'null' }] });

const syncFields = {
  id: { type: 'string', maxLength: 120 },
  serverId: nullableString(120),
  syncStatus: { type: 'string', enum: ['pending', 'syncing', 'synced', 'failed', 'conflict'] },
  syncError: nullableString(4096),
  offlineCreated: { type: 'boolean' },
  deletedAt: nullableString(40),
  lastSyncedAt: nullableString(40),
  createdAt: { type: 'string', maxLength: 40 },
  updatedAt: { type: 'string', maxLength: 40 },
} as const;

const syncRequired = [
  'id',
  'serverId',
  'syncStatus',
  'syncError',
  'offlineCreated',
  'deletedAt',
  'lastSyncedAt',
  'createdAt',
  'updatedAt',
] as const;

export const householdSchema: RxJsonSchema<LocalHousehold> = {
  title: 'ministry planner local household',
  version: 0,
  primaryKey: 'id',
  type: 'object',
  keyCompression: false,
  additionalProperties: false,
  properties: {
    ...syncFields,
    congregationId: nullableString(120),
    territoryId: nullableString(120),
    address: { type: 'string', maxLength: 512 },
    houseNumber: nullableString(80),
    unitNumber: nullableString(80),
    streetName: { type: 'string', maxLength: 512 },
    city: { type: 'string', maxLength: 255 },
    postalCode: nullableString(80),
    country: nullableString(120),
    latitude: nullableString(40),
    longitude: nullableString(40),
    type: { type: 'string', maxLength: 80 },
    floor: nullableNumber(),
    occupantsCount: nullableNumber(),
    languages: nullableString(1024),
    bestTimeToCall: nullableString(255),
    status: { type: 'string', maxLength: 80 },
    lastVisitDate: nullableString(40),
    lastVisitOutcome: nullableString(80),
    notes: nullableString(8192),
    lwpNotes: nullableString(8192),
    createdById: nullableString(120),
    updatedById: nullableString(120),
  },
  required: [
    ...syncRequired,
    'congregationId',
    'territoryId',
    'address',
    'houseNumber',
    'unitNumber',
    'streetName',
    'city',
    'postalCode',
    'country',
    'latitude',
    'longitude',
    'type',
    'floor',
    'occupantsCount',
    'languages',
    'bestTimeToCall',
    'status',
    'lastVisitDate',
    'lastVisitOutcome',
    'notes',
    'lwpNotes',
    'createdById',
    'updatedById',
  ],
  indexes: ['serverId', 'territoryId', 'congregationId', 'syncStatus', 'deletedAt', 'updatedAt'],
};

export const visitSchema: RxJsonSchema<LocalVisit> = {
  title: 'ministry planner local visit',
  version: 0,
  primaryKey: 'id',
  type: 'object',
  keyCompression: false,
  additionalProperties: false,
  properties: {
    ...syncFields,
    userId: nullableString(120),
    householdId: { type: 'string', maxLength: 120 },
    householdServerId: nullableString(120),
    visitDate: { type: 'string', maxLength: 40 },
    outcome: { type: 'string', maxLength: 80 },
    householdStatusBefore: nullableString(80),
    householdStatusAfter: nullableString(80),
    duration: nullableNumber(),
    literatureLeft: nullableString(2048),
    bibleTopicDiscussed: nullableString(512),
    returnVisitPlanned: { type: 'boolean' },
    nextVisitDate: nullableString(40),
    nextVisitNotes: nullableString(4096),
    assignmentId: nullableString(120),
    notes: nullableString(8192),
  },
  required: [
    ...syncRequired,
    'userId',
    'householdId',
    'householdServerId',
    'visitDate',
    'outcome',
    'householdStatusBefore',
    'householdStatusAfter',
    'duration',
    'literatureLeft',
    'bibleTopicDiscussed',
    'returnVisitPlanned',
    'nextVisitDate',
    'nextVisitNotes',
    'assignmentId',
    'notes',
  ],
  indexes: ['serverId', 'householdId', 'householdServerId', 'syncStatus', 'deletedAt', 'visitDate'],
};

export const encounterSchema: RxJsonSchema<LocalEncounter> = {
  title: 'ministry planner local encounter',
  version: 0,
  primaryKey: 'id',
  type: 'object',
  keyCompression: false,
  additionalProperties: false,
  properties: {
    ...syncFields,
    userId: nullableString(120),
    visitId: nullableString(120),
    visitServerId: nullableString(120),
    householdId: nullableString(120),
    householdServerId: nullableString(120),
    encounterDate: { type: 'string', maxLength: 40 },
    name: nullableString(255),
    gender: nullableString(40),
    ageGroup: nullableString(60),
    role: nullableString(80),
    response: { type: 'string', maxLength: 80 },
    languageSpoken: nullableString(120),
    topicDiscussed: nullableString(512),
    literatureAccepted: nullableString(2048),
    bibleStudyInterest: { type: 'boolean' },
    returnVisitRequested: { type: 'boolean' },
    nextVisitNotes: nullableString(4096),
    notes: nullableString(8192),
  },
  required: [
    ...syncRequired,
    'userId',
    'visitId',
    'visitServerId',
    'householdId',
    'householdServerId',
    'encounterDate',
    'name',
    'gender',
    'ageGroup',
    'role',
    'response',
    'languageSpoken',
    'topicDiscussed',
    'literatureAccepted',
    'bibleStudyInterest',
    'returnVisitRequested',
    'nextVisitNotes',
    'notes',
  ],
  indexes: ['serverId', 'visitId', 'householdId', 'syncStatus', 'deletedAt', 'encounterDate'],
};

export const avatarUploadSchema: RxJsonSchema<LocalAvatarUpload> = {
  title: 'ministry planner local avatar upload',
  version: 0,
  primaryKey: 'id',
  type: 'object',
  keyCompression: false,
  additionalProperties: false,
  properties: {
    id: { type: 'string', maxLength: 120 },
    userId: { type: 'string', maxLength: 120 },
    fileName: { type: 'string', maxLength: 255 },
    mimeType: { type: 'string', maxLength: 120 },
    dataUrl: { type: 'string' },
    syncStatus: { type: 'string', enum: ['pending', 'syncing', 'synced', 'failed', 'conflict'] },
    syncError: nullableString(4096),
    createdAt: { type: 'string', maxLength: 40 },
    updatedAt: { type: 'string', maxLength: 40 },
    lastSyncedAt: nullableString(40),
  },
  required: [
    'id',
    'userId',
    'fileName',
    'mimeType',
    'dataUrl',
    'syncStatus',
    'syncError',
    'createdAt',
    'updatedAt',
    'lastSyncedAt',
  ],
  indexes: ['userId', 'syncStatus', 'updatedAt'],
};